import type { Event, Recipient } from '../db/schema';

/**
 * Post-event feedback email. Includes one link per star-rating (1-5) plus a
 * "didn't attend" link. Links are signed tokens generated by the caller.
 */
export function postEventFeedbackEmail(args: {
  recipient: Recipient;
  event: Event;
  links: {
    goingNo: string;
    going1: string;
    going2: string;
    going3: string;
    going4: string;
    going5: string;
  };
}): { subject: string; html: string; text: string } {
  const { recipient, event, links } = args;
  const when = event.startsAt
    ? new Date(event.startsAt).toLocaleString('en-NZ', { dateStyle: 'medium', timeStyle: 'short' })
    : 'recently';

  const subject = `How was ${event.title}?`;

  const text = [
    `Hey ${recipient.displayName},`,
    '',
    `${event.title} (${when}) — did you make it?`,
    '',
    'If you went, how was it? (tap to rate)',
    `★☆☆☆☆ 1 — pretty rough: ${links.going1}`,
    `★★☆☆☆ 2 — meh:          ${links.going2}`,
    `★★★☆☆ 3 — decent:       ${links.going3}`,
    `★★★★☆ 4 — great night:   ${links.going4}`,
    `★★★★★ 5 — absolutely:    ${links.going5}`,
    '',
    `Didn't end up going: ${links.goingNo}`,
  ].join('\n');

  const html = `
<!doctype html><html><body style="font-family:system-ui,-apple-system,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#111">
<p>Hey ${escapeHtml(recipient.displayName)},</p>
<p><strong>${escapeHtml(event.title)}</strong> (${escapeHtml(when)}) — did you make it?</p>
<p>How was it? Tap to rate:</p>
<p style="margin:20px 0;line-height:2.2">
  <a href="${links.going1}" style="${btnStyle('#b91c1c')}">★☆☆☆☆ 1 — rough</a>&nbsp;
  <a href="${links.going2}" style="${btnStyle('#c2410c')}">★★☆☆☆ 2 — meh</a>&nbsp;
  <a href="${links.going3}" style="${btnStyle('#b45309')}">★★★☆☆ 3 — decent</a>&nbsp;
  <a href="${links.going4}" style="${btnStyle('#15803d')}">★★★★☆ 4 — great</a>&nbsp;
  <a href="${links.going5}" style="${btnStyle('#1d4ed8')}">★★★★★ 5 — loved it</a>
</p>
<p style="font-size:13px;color:#555">Didn't end up going? <a href="${links.goingNo}" style="color:#6b7280">Let us know</a>.</p>
</body></html>`.trim();

  return { subject, html, text };
}

function btnStyle(bg: string): string {
  return `display:inline-block;padding:10px 16px;background:${bg};color:#fff;text-decoration:none;border-radius:6px;margin-bottom:4px`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
}
